### ISSUE TITLE
server error

### ISSUE THREAD

**Issue by gautamkrishnar** [berkerpeksag/github-badge#87] opened 2016-09-18 21:12 UTC
Error: Server Error
The server encountered an error and could not complete your request.

Please try again in 30 seconds.

See the url: http://githubbadge.appspot.com/gautamkrishnar

**Comment by jayvdb** [comment] 2016-09-28 22:21
I see the same problem: http://githubbadge.appspot.com/jayvdb

**Comment by jayvdb** [comment] 2016-10-03 11:58
Maybe related to #76

**Comment by cncoder** [comment] 2017-03-25 20:18
I see the same problem: https://githubbadge.appspot.com/cncoder

**Comment by gautamkrishnar** [comment] 2017-04-19 20:16
Still not fixed😢

**Comment by berkerpeksag** [comment] 2019-04-19 19:54
Closing as a duplicate of #86. Thank you for the all feedback!

**Closed by berkerpeksag** 2019-04-19 19:54 UTC
