### ISSUE TITLE
server error

### ISSUE THREAD

**Issue by k-okada** [berkerpeksag/github-badge#76] opened 2015-01-10 10:05 UTC
Hi, 

I can get my badge, why?
http://githubbadge.appspot.com/k-okada

**Comment by BYK** [comment] 2015-01-12 13:57
I think this repo is blowing it up: https://github.com/k-okada/catkin

We don't have a proper thread pool nor a queue system to generate the badge, that's the reason. The memory usage goes high (above 128 MB) and Google shuts the process down.

**Comment by lirantal** [comment] 2016-02-16 22:12
I'm also reporting the same issue...
Server response is actually:
![image](https://cloud.githubusercontent.com/assets/316371/13092929/29e9d6a8-d50b-11e5-910f-1cce595cd5d3.png)

**Comment by BYK** [comment] 2016-02-16 22:14
Oooh, I guess it finally happened.

**Comment by BYK** [comment] 2016-02-16 22:21
Looks like we're over quota for incoming traffic. So the site will be down for the next 10 hours. Not sure how we can reduce the data we fetch from GitHub. @berkerpeksag, thoughts?

**Comment by leniel** [comment] 2017-02-02 03:05
Same problem right now... this is the first time I see this:

http://githubbadge.appspot.com/leniel

Over Quota

This application is temporarily over its serving quota. Please try again later.

**Comment by berkerpeksag** [comment] 2019-04-19 19:54
Closing as a duplicate of #86. Thank you for the all feedback!

**Closed by berkerpeksag** 2019-04-19 19:54 UTC
